In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## Define the vocabulary size
voc_size=10000

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8261, 3543, 716, 7733],
 [8261, 3543, 716, 7422],
 [8261, 5948, 716, 8424],
 [5730, 5346, 7091, 8714, 9832],
 [5730, 5346, 7091, 8714, 578],
 [8500, 8261, 1222, 716, 5482],
 [4100, 7250, 7117, 8714]]

In [15]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
import numpy as np

In [23]:
sent_length=8                                    #post
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8261 3543  716 7733]
 [   0    0    0    0 8261 3543  716 7422]
 [   0    0    0    0 8261 5948  716 8424]
 [   0    0    0 5730 5346 7091 8714 9832]
 [   0    0    0 5730 5346 7091 8714  578]
 [   0    0    0 8500 8261 1222  716 5482]
 [   0    0    0    0 4100 7250 7117 8714]]


In [25]:
## feature representation
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 235ms/step


array([[[ 0.02831009, -0.04371211,  0.03483443, -0.00068263,
         -0.00125923,  0.02503205,  0.03738052, -0.04889433,
          0.03502624, -0.00821813],
        [ 0.02831009, -0.04371211,  0.03483443, -0.00068263,
         -0.00125923,  0.02503205,  0.03738052, -0.04889433,
          0.03502624, -0.00821813],
        [ 0.02831009, -0.04371211,  0.03483443, -0.00068263,
         -0.00125923,  0.02503205,  0.03738052, -0.04889433,
          0.03502624, -0.00821813],
        [ 0.02831009, -0.04371211,  0.03483443, -0.00068263,
         -0.00125923,  0.02503205,  0.03738052, -0.04889433,
          0.03502624, -0.00821813],
        [-0.02773788, -0.00426062,  0.01395487, -0.01953483,
         -0.02066401,  0.00615376, -0.00988233,  0.00536563,
         -0.04463284,  0.03775953],
        [-0.00984945,  0.04592508, -0.02799   ,  0.04217117,
         -0.01662816,  0.04874697, -0.04203845,  0.02578291,
          0.04291025, -0.03978611],
        [ 0.02786383,  0.02603251,  0.0221393 ,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5423, 7729, 6702, 8885])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


array([[-0.01786195, -0.04990674, -0.00179753,  0.0434049 ,  0.03149397,
        -0.01340045,  0.03313382,  0.00847621,  0.0153268 ,  0.02206158],
       [-0.01786195, -0.04990674, -0.00179753,  0.0434049 ,  0.03149397,
        -0.01340045,  0.03313382,  0.00847621,  0.0153268 ,  0.02206158],
       [-0.01786195, -0.04990674, -0.00179753,  0.0434049 ,  0.03149397,
        -0.01340045,  0.03313382,  0.00847621,  0.0153268 ,  0.02206158],
       [-0.01786195, -0.04990674, -0.00179753,  0.0434049 ,  0.03149397,
        -0.01340045,  0.03313382,  0.00847621,  0.0153268 ,  0.02206158],
       [-0.00065149, -0.02139112, -0.03625585, -0.00469495, -0.0391903 ,
         0.03379563,  0.02926021,  0.01059856,  0.03554534, -0.01968604],
       [-0.03110213, -0.01215788,  0.03299756, -0.02743625, -0.0026674 ,
        -0.01954786,  0.02092507,  0.04768834, -0.02658653,  0.0456954 ],
       [ 0.019694  , -0.01728579, -0.02054436,  0.04440105,  0.00131102,
        -0.03085184,  0.0160397 , -0.01064718